export const role = [
  { group: "ENGINEERING", title: "Backend" },
  { group: "ENGINEERING", title: "Frontend" },
  { group: "ENGINEERING", title: "Fullstack" },
  { group: "ENGINEERING", title: "IOS" },
  { group: "ENGINEERING", title: "Flutter" },
  { group: "ENGINEERING", title: "React Native" },
  { group: "ENGINEERING", title: "Android" },
  { group: "ENGINEERING", title: "Tech-Lead" },
  { group: "ENGINEERING", title: "Dev-Ops" },
  { group: "ENGINEERING", title: "Data Engineer" },
  { group: "ENGINEERING", title: "Data Science" },
  { group: "ENGINEERING", title: "Computer-Vision" },
  { group: "ENGINEERING", title: "NLP" },
  { group: "ENGINEERING", title: "Test / Qa" },
  { group: "ENGINEERING", title: "Deep Learning" },
  { group: "ENGINEERING", title: "Sre" },
  { group: "ENGINEERING", title: "Data-Infrastructure" },
  { group: "DESIGN", title: "Designer" },
  { group: "DESIGN", title: "Design Manager" },
  { group: "DESIGN", title: "Graphic Designer" },
  { group: "DESIGN", title: "Product Designer" },
  { group: "PRODUCT", title: "Product Manager" },
  { group: "OPERATIONS", title: "Operations Manager" },
  { group: "OPERATIONS", title: "Founder's Office/Cheif Of Staff" },
  { group: "SALES", title: "Sales Development Representative" },
  { group: "SALES", title: "Account Executive" },
  { group: "SALES", title: "Account Manager" },
  { group: "MARKETING", title: "Digital Marketing Manager" },
  { group: "MARKETING", title: "Growth Hacker" },
  { group: "MARKETING", title: "Marketing" },
  { group: "MARKETING", title: "Product Marketing Manager" },
  { group: "OTHER ENGINEERING", title: "Hardware" },
  { group: "OTHER ENGINEERING", title: "Mechanical" },
  { group: "OTHER ENGINEERING", title: "Systems" },
  { group: "BUSINESS ANALYST", title: "Business Analyst" },
  { group: "DATA ANALYST", title: "Data Analyst" },
  { group: "PROJECT MANAGER", title: "Project Manager" },
  { group: "MANAGEMENT", title: "Management" },
  { group: "LEGAL", title: "Legal" },
  { group: "HR", title: "Hr" },
  { group: "FINANCE", title: "Finance" },
];

export const numberOfEmployees = [
  { title: "1-10" },
  { title: "11-20" },
  { title: "21-50" },
  { title: "51-100" },
  { title: "101-200" },
  { title: "201-500" },
  { title: "500+" },
];

export const experience = [
  { title: "1" },
  { title: "2" },
  { title: "3" },
  { title: "4" },
  { title: "5" },
  { title: "6" },
  { title: "7" },
  { title: "8" },
  { title: "9" },
  { title: "10" },
];
export const remote = [
  { title: "Remote" },
  { title: "Hybrid" },
  { title: "In-Office" },
];
export const minPay = [
  { title: "0L" },
  { title: "10L" },
  { title: "20L" },
  { title: "30L" },
  { title: "40L" },
  { title: "50L" },
  { title: "60L" },
  { title: "70L" },
];
